### ISSUE TITLE
How to implement if your model already has a default manager?

### ISSUE THREAD

**Issue by picturedots** [vijaykatam/django-cache-manager#13]
I was wondering what is recommended approach for this using this if I already have a default manager for my objects, i.e.

    class MyModels(models.Model):
        ...
        objects = MyManager()

Should "MyManager" inherit from "CacheManager"?  And what if I already have an inheritance chain for "MyManager"?  thanks

**Comment by vijaykatam** [comment]
One option is your model can inherit from "CacheManager" and set "MyManager" as default, another option which I would recommend is creating a mixin for your model that has the methods that "MyManager" is providing and set "CacheManager" as the default.
