### ISSUE TITLE
'TIMEOUT': 0 for FileBasedCache

### ISSUE THREAD

**Issue by Sovetnikov** [vijaykatam/django-cache-manager#21]
On main page in your sample cache config, TIMEOUT is set to 0 - but this means "don't cache".

From django docs(https://docs.djangoproject.com/en/1.10/topics/cache/):
TIMEOUT: The default timeout, in seconds, to use for the cache. This argument defaults to 300 seconds (5 minutes). You can set TIMEOUT to None so that, by default, cache keys never expire. A value of 0 causes keys to immediately expire (effectively “don’t cache”).

**Comment by vijaykatam** [comment]
I have updated the doc, thanks for pointing out. Just so that you know you should always be using a centralized cache infrastructure such as Memcache or Redis.
