### ISSUE TITLE
Update readme to specify cache manager needs to be default

### ISSUE THREAD

**Issue by vijaykatam** [vijaykatam/django-cache-manager#3]
If cache manager is not default then cache eviction for related model queries will not work as expected.

**Comment by tushar-thantharate** [comment]
Is the package production stable?

**Comment by vijaykatam** [comment]
@tushar-thantharate we are currently swapping out johnny-cache with this package

**Comment by tushar-thantharate** [comment]
@vijaykatam Please let me know when you the production stable release. Thanks +1

**Comment by vijaykatam** [comment]
Readme cleaned up
